
FROM ubuntu:22.04 AS builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
   build-essential \
    cmake \
    git \
    curl \
    pkg-config \
    zip \
    unzip \
    tar \
    libpq-dev \
    libssl-dev \
    zlib1g-dev \
    bison \
    flex \
    autoconf \
    libreadline-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /opt
RUN git clone https://github.com/microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh

RUN /opt/vcpkg/vcpkg install cpp-httplib libpqxx

WORKDIR /app
COPY CMakeLists.txt main.cpp ./

RUN cmake -B build -S . \
    -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DCMAKE_BUILD_TYPE=Release \
 && cmake --build build --config Release

WORKDIR /app/build
ENTRYPOINT ["./server_app"]
